config/routes.rb
Rails.application.routes.draw do

  # index for guests
  get '/guests' => 'guests#index'
  # new
  get '/guests/new' => 'guests#new'
  # create
  post '/guests' => 'guests#create'
  # show
  get '/guests/:id' => 'guests#show'
  # edit
  get '/guests/:id/edit' => 'guests#edit'
  # update
  put '/guests/:id' => 'guests#update'
  patch '/guests/:id' => 'guests#update'
  # delete/destroy
  delete '/guests/:id' => 'guests#destroy'

  # index for memberships
  get '/memberships' => 'memberships#index'
  # new
  get '/memberships/new' => 'memberships#new'
  # create
  post '/memberships' => 'memberships#create'
  # show
  get '/memberships/:id' => 'memberships#show'
  # edit
  get '/memberships/:id/edit' => 'memberships#edit'
  # update
  put '/memberships/:id' => 'memberships#update'
  patch '/memberships/:id' => 'memberships#update'
  # delete/destroy
  delete '/memberships/:id' => 'memberships#destroy'

  # index for membersclubs
  get '/membersclubs' => 'membersclubs#index'
  # new
  get '/membersclubs/new' => 'membersclubs#new'
  # create
  post '/membersclubs' => 'membersclubs#create'
  # show
  get '/membersclubs/:id' => 'membersclubs#show'
  # edit
  get '/membersclubs/:id/edit' => 'membersclubs#edit'
  # update
  put '/membersclubs/:id' => 'membersclubs#update'
  patch '/membersclubs/:id' => 'membersclubs#update'
  # delete/destroy
  delete '/membersclubs/:id' => 'membersclubs#destroy'
  
end

app/models/drink.rb
class Drink < ActiveRecord::Base
  belongs_to :membersclub
  belongs_to :guest
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :viplounge
  has_many :guests, through :viplounge
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  has_many :membersclubs, through: :membership
  has_many :drinks, through: :order
  has_many :events, through: :viplounge
end

app/models/membersclub.rb
class Membersclub < ActiveRecord::Base
  has_many :guests, through: :membership
  has_many :drinks, through: :order
  has_one :viplounge
  has_many :events, through: :viplounge
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  has_many :guests
  has_many :membersclubs
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :guests
  has_many :drinks
  has_many :membersclubs
end

app/models/viplounge.rb
class Viplounge < ActiveRecord::Base
  belongs_to :membersclub
  has_many :events
  has_many :guests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  def index
    @guests = Guest.all.order('created_at DESC')
  end

  def new
    @guest = Guest.new
  end

  def create
    guest = Guest.new(guest_params)
    
    if guest.save
      flash[:notice] = 'Guest created successfully!'
      redirect_to guest
    else
      flash.now[:error] = "Error: #{guest.errors.full_messages}"
      render :new
    end
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def update
    guest = Guest.find(params[:id])

    if guest.update(guest_params)
      redirect_to guest
    else
      render :edit
    end
  end

  def destroy
    guest = Guest.find(params[:id]).destroy

    redirect_to root_path
  end

end

app/controllers/membersclubs_controller.rb
class MembersclubsController < ApplicationController

  def index
    @membersclubs = Membersclub.all.order('created_at DESC')
  end

  def new
    @membersclub = Membersclub.new
  end

  def create
    membersclub = Membersclub.new(membersclub_params)
    
    if membersclub.save
      flash[:notice] = 'Membersclub created successfully!'
      redirect_to membersclub
    else
      flash.now[:error] = "Error: #{membersclub.errors.full_messages}"
      render :new
    end
  end

  def show
    @membersclub = Membersclub.find(params[:id])
  end

  def edit
    @membersclub = Membersclub.find(params[:id])
  end

  def update
    membersclub = Membersclub.find(params[:id])

    if membersclub.update(membersclub_params)
      redirect_to membersclub
    else
      render :edit
    end
  end

  def destroy
    membersclub = Membersclub.find(params[:id]).destroy

    redirect_to root_path
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  def index
    @memberships = Membership.all.order('created_at DESC')
  end

  def new
    @membership = Membership.new
  end

  def create
    membership = Membership.new(membership_params)
    
    if membership.save
      flash[:notice] = 'Membership created successfully!'
      redirect_to membership
    else
      flash.now[:error] = "Error: #{membership.errors.full_messages}"
      render :new
    end
  end

  def show
    @membership = Membership.find(params[:id])
  end

  def edit
    @membership = Membership.find(params[:id])
  end

  def update
    membership = Membership.find(params[:id])

    if membership.update(membership_params)
      redirect_to membership
    else
      render :edit
    end
  end

  def destroy
    membership = Membership.find(params[:id]).destroy

    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/guests/edit.html.erb
<%= form_for @guest do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>
  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>
  <div class="action">
    <%= form.submit 'Update Guest' %>
  </div>

<% end %>

app/views/guests/index.html.erb
<h1>index</h1>

<% @guests.each do |guest| %>
  <h2><%= link_to guest.name, guest %></h2>
<% end %>

app/views/guests/new.html.erb
<%= form_for @guest do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>
  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>
  <div class="action">
    <%= form.submit 'Add a new guest' %>
  </div>

<% end %>

app/views/guests/show.html.erb
<h1><%= @guest.name %></h1>
<h2><%= @guest.gender %></h2>
<p><%= @guest.age %></p>


<%= link_to 'Edit', edit_guest_path(@guest) %>
<%= link_to 'Delete', @guest, method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Club</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/membersclubs/edit.html.erb
<%= form_for @membersclub do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>
  <div class="action">
    <%= form.submit 'Update Club' %>
  </div>

<% end %>

app/views/membersclubs/index.html.erb
<h1>index</h1>

<% @membersclubs.each do |membersclub| %>
  <h2><%= link_to membersclub.name, membersclub %></h2>
<% end %>

app/views/membersclubs/new.html.erb
<%= form_for @membersclub do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>
  <div class="action">
    <%= form.submit 'Create a new club' %>
  </div>

<% end %>

app/views/membersclubs/show.html.erb
<h1><%= @membersclub.name %></h1>
<h2><%= @membersclub.location %></h2>
<h3><%= @membersclub.genre %></h3>

<%= link_to 'Edit', edit_membersclub_path(@membersclub) %>
<%= link_to 'Delete', @membersclub, method: :delete, data: { confirm: "Are you sure?" } %>

app/views/memberships/edit.html.erb
<%= form_for @membership do |form| %>
  <div class="field">
    <%= form.label :guest_id %>
    <%= form.text_field :guest_id %>
  </div>
  <div class="field">
    <%= form.label :membersclub_id %>
    <%= form.text_field :membersclub_id %>
  </div>
  <div class="action">
    <%= form.submit 'Update Membership' %>
  </div>

<% end %>

app/views/memberships/index.html.erb
<h1>index</h1>

<% @memberships.each do |membership| %>
  <h2><%= link_to membership.membership_id, membership %></h2>
<% end %>

app/views/memberships/new.html.erb
<%= form_for @membership do |form| %>
  <div class="field">
    <%= form.label :guest_id %>
    <%= form.text_field :guest_id %>
  </div>
  <div class="field">
    <%= form.label :membersclub_id %>
    <%= form.text_field :membersclub_id %>
  </div>
  <div class="action">
    <%= form.submit 'Create a new membership' %>
  </div>

<% end %>

app/views/memberships/show.html.erb
<h1><%= @membership.guest_id %></h1>
<h2><%= @membership.membersclub_id %></h2>

<%= link_to 'Edit', edit_membership_path(@membership) %>
<%= link_to 'Delete', @membership, method: :delete, data: { confirm: "Are you sure?" } %>